version: "3.2"
services:
    php:
        build:
            context: .
        image: bricx_carasco/samplephpapp:1.0.0
        networks:
            - frontend
            - backend
        environment:
            - MYSQL_HOST=bricxdockermysqlapp
            - MYSQL_USER=bricx
            - MYSQL_PASSWORD=123456
            - MYSQL_DATABASE=phpsample
        volumes:
            - ./www/public:/var/www/html/
        ports:
            - "3001:80"
        container_name: bricxdockerphpapp
    mysql:
        image: mysql:5.7
        networks:
            - backend
        environment:
            - MYSQL_ROOT_PASSWORD=rootpassword
            - MYSQL_USER=bricx
            - MYSQL_PASSWORD=123456
            - MYSQL_DATABASE=phpsample
        container_name: bricxdockermysqlapp
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.7
        depends_on:
            - mysql
        networks:
            - backend
        ports:
            - "3002:80"
        environment:
            - PMA_HOST=bricxdockermysqlapp
            - PMA_PORT=3306
        volumes:
            - /sessions
        container_name: bricxdockerphpmyadminapp
networks:
    frontend:
    backend:
